[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools-ocrd"]

[project]
name = "eynollah"
authors = [
    {name = "Vahid Rezanezhad"},
    {name = "Staatsbibliothek zu Berlin - Preußischer Kulturbesitz"},
]
description = "Document Layout Analysis"
readme = "README.md"
license.file = "LICENSE"
requires-python = ">=3.9"
keywords = [
    "document layout analysis",
    "image segmentation",
    "binarization",
    "optical character recognition"
]

dynamic = [
  "dependencies",
  "optional-dependencies",
  "version"
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: Image Processing",
]

[project.scripts]
eynollah = "eynollah.cli:main"
eynollah-training = "eynollah.training.cli:main"
ocrd-eynollah-segment = "eynollah.ocrd_cli:main"
ocrd-sbb-binarize = "eynollah.ocrd_cli_binarization:main"

[project.urls]
Homepage = "https://github.com/qurator-spk/eynollah"
Repository = "https://github.com/qurator-spk/eynollah.git"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
optional-dependencies.test = {file = ["requirements-test.txt"]}
optional-dependencies.OCR = {file = ["requirements-ocr.txt"]}
optional-dependencies.plotting = {file = ["requirements-plotting.txt"]}
optional-dependencies.training = {file = ["requirements-training.txt"]}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.json", '*.yml', '*.xml', '*.xsd', '*.ttf']

[tool.coverage.run]
branch = true
source = ["eynollah"]

[tool.ruff]
line-length = 120
src = ["src/eynollah"]
include = ["pyproject.toml", "src/eynollah/**/*.py"]
extend-exclude = ["src/eynollah/training/*.py"]

[tool.ruff.lint]
ignore = [
# disable unused imports
"F401",
# disable import order
"E402",
# Import block is un-sorted or un-formatted
"I001",
# disable unused variables
"F841",
# Use format specifiers instead of percent format
"UP031",
# `datetime.datetime.now()` called without a `tz` argument
"DTZ005",
# Unnecessary `dict()` call
"C408",
# Unpacked variable is never used (seem overly restrictive - we may refer to it in commented code)
"RUF059",
# Contains chained boolean comparison that can be simplified (style cannot be negotiated; we may need this for clarity)
"PLR1716",
# Use a single `if` statement instead of nested `if` statements (we may want consistent indentation)
"SIM102",
# Create your own exception (generic Exception ok for now)
"TRY002",
# Do not catch blind exception: `Exception` (TODO: drop)
"BLE001",
# disable bare except (TODO: drop)
"E722",
# `try`-`except`-`pass` detected, consider logging the exception (TODO: drop)
"S110",
]

[tool.ruff.format]
quote-style = "preserve"

